webdev/tarefas/urls.py
from django.urls import path
from . import views

app_name = 'tarefas'

urlpatterns = [
    path('', views.home, name='home')
]

webdev/urls.py
from django.contrib import admin
from django.urls import path, include
from webdev.home_view import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('tarefas/', include('webdev.tarefas.urls')),
]

webdev/tarefas/models.py
from django.db import models


class Tarefa(models.Model):
    nome = models.CharField(max_length=128)
    feita = models.BooleanField(default=False)

webdev/tarefas/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'tarefas/home.html')

webdev/tarefas/templates/tarefas/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Tarefas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mt-5">Lista de Tarefas</h1>

            <form action="{% url 'tarefas:home' %}" method="post">
                {% csrf_token %}

                <div class="input-group mb-3">
                  <input type="text" class="form-control" placeholder="Descreva sua tarefa"
                         aria-label="Descreva sua tarefa" aria-describedby="button-addon2" name="nome">
                  <button type="submit" class="btn btn-primary" id="button-addon2">Salvar</button>
                </div>
            </form>

        </div>
    </div>
</div>
</body>
</html>